apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: cyberlab-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyberlab-backend
  template:
    metadata:
      labels:
        app: cyberlab-backend
    spec:
      serviceAccountName: lab-manager
      imagePullSecrets:
        - name: cyberlab-registry 
      containers:
      - name: backend
        image: registry.digitalocean.com/cyberlab-registry/cyberlab-backend:main-223d2fb
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: connection-string
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JWT_EXPIRE
          value: "7d"
        - name: K8S_NAMESPACE
          value: "student-labs" 
        - name: LAB_IMAGE
          value: "registry.digitalocean.com/cyberlab-registry/ubuntu-desktop-lab:main-6685f13"
        - name: LAB_SESSION_TIMEOUT
          value: "7200000"
        - name: MAX_CONCURRENT_LABS
          value: "3"
        # Ingress configuration for secure lab access
        - name: LAB_DOMAIN
          value: "labs.152-42-156-112.nip.io"  # Subdomain for student labs
        - name: LAB_PROTOCOL
          value: "http"  # Use HTTP due to Let's Encrypt rate limits on nip.io
        # Email configuration for student registration
        - name: EMAIL_HOST
          value: "smtp.gmail.com"  # Change to your SMTP server
        - name: EMAIL_PORT
          value: "465"  # Using SSL port (587 is blocked by DigitalOcean)
        - name: EMAIL_SECURE
          value: "true"  # Use SSL instead of STARTTLS
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: username
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: password
        - name: EMAIL_FROM_NAME
          value: "CyberLab Admin"
        - name: FRONTEND_URL
          value: "https://152-42-156-112.nip.io"  # Your frontend URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: cyberlab-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: cyberlab-backend