apiVersion: v1
kind: Namespace
metadata:
  name: student-labs
  labels:
    name: student-labs
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: student-labs-quota
  namespace: student-labs
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "100"
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: student-labs-limits
  namespace: student-labs
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container