apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  connection-string: "mongodb+srv://mongo_source:0S82imYCk6te4vkC@devwork.8uo5f.mongodb.net/cyberlab?retryWrites=true&w=majority&appName=devwork"
  # ☝️ REPLACE with your actual MongoDB Atlas connection string
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: "hdhdgdgdhdhdgshasyuyeuehsb"
  # ☝️ REPLACE with a secure random string