name: Frontend CI/CD

on:
    push:
        branches:
            - main
            - develop
        paths:
            - "frontend/**"
            - "docker/frontend/**"
            - ".github/workflows/frontend.yml"
    pull_request:
        branches:
            - main
            - develop
        paths:
            - "frontend/**"
            - "docker/frontend/**"

env:
    REGISTRY: registry.digitalocean.com
    REGISTRY_NAME: cyberlab-registry
    IMAGE_NAME: cyberlab-frontend
    ARGOCD_REPO: ${{ github.repository }}

jobs:
    # Job 1: Build and Test
    build-and-test:
        name: Build & Test Frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Run linter
              working-directory: ./frontend
              run: npm run lint
              continue-on-error: true

            - name: Build frontend
              working-directory: ./frontend
              run: npm run build
              env:
                  NODE_ENV: production

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: frontend/dist
                  retention-days: 1

    # Job 2: Build and Push Docker Image
    docker-build-push:
        name: Build & Push Docker Image
        needs: build-and-test
        runs-on: ubuntu-latest
        if: github.event_name == 'push'

        permissions:
            contents: read
            packages: write

        outputs:
            image-tag: ${{ steps.meta.outputs.tags }}
            image-digest: ${{ steps.build.outputs.digest }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DigitalOcean Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.DIGITALOCEAN_TOKEN }}
                  password: ${{ secrets.DIGITALOCEAN_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix={{branch}}-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              id: build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/frontend/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache
                  cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

    # Job 3: Update ArgoCD Manifests
    update-manifests:
        name: Update K8s Manifests
        needs: docker-build-push
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update image tag in deployment
              run: |
                  IMAGE_TAG="${GITHUB_SHA::7}"
                  sed -i "s|image: registry.digitalocean.com/cyberlab-registry/cyberlab-frontend:.*|image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:main-${IMAGE_TAG}|g" kubernetes/frontend/deployment.yaml

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add kubernetes/frontend/deployment.yaml
                  git commit -m "Update frontend image to main-${GITHUB_SHA::7}" || echo "No changes to commit"
                  git push

    # Job 4: Notify ArgoCD (Optional)
    notify-argocd:
        name: Sync ArgoCD
        needs: update-manifests
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Trigger ArgoCD Sync
              run: |
                  # Install ArgoCD CLI
                  curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
                  chmod +x /usr/local/bin/argocd

                  # Login to ArgoCD
                  argocd login ${{ secrets.ARGOCD_SERVER }} \
                    --username ${{ secrets.ARGOCD_USERNAME }} \
                    --password ${{ secrets.ARGOCD_PASSWORD }} \
                    --insecure

                  # Sync application
                  argocd app sync frontend-app --prune
              continue-on-error: true
