name: Ubuntu Desktop CI/CD

on:
    push:
        branches:
            - main
        paths:
            - "docker/ubuntu-desktop/**"
            - ".github/workflows/ubuntu-desktop.yml"
    workflow_dispatch: # Allow manual trigger

env:
    REGISTRY: registry.digitalocean.com
    REGISTRY_NAME: cyberlab-registry
    IMAGE_NAME: ubuntu-desktop-lab

jobs:
    docker-build-push:
        name: Build & Push Ubuntu Desktop Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DigitalOcean Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.DIGITALOCEAN_TOKEN }}
                  password: ${{ secrets.DIGITALOCEAN_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix={{branch}}-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./docker/ubuntu-desktop
                  file: ./docker/ubuntu-desktop/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache
                  cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

            - name: Update backend deployment (if using versioned tags)
              if: github.ref == 'refs/heads/main'
              run: |
                  IMAGE_TAG="${GITHUB_SHA::7}"
                  sed -i "s|value: \"registry.digitalocean.com/cyberlab-registry/ubuntu-desktop-lab:.*\"|value: \"${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:main-${IMAGE_TAG}\"|g" kubernetes/backend/deployment.yaml

                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add kubernetes/backend/deployment.yaml
                  git commit -m "Update ubuntu-desktop image to main-${GITHUB_SHA::7}" || echo "No changes"
                  git push || echo "No changes to push"
              continue-on-error: true
